### PR TITLE
Add "Married to non-staff"; do not prompt for spouse

### PR DESCRIPTION
**Pull request by knutsenm**
I don't know how to test this, or how to update translation files

### CODE REVIEW

**Comment by Omicron7** [comment]
👍 
`gulp onesky` will regenerate the .pot and upload it to onesky.

**Comment by Omicron7** [comment]
and there is currently no testing in this project. It's possible to run locally and test, or push changes to stage branch to build stage container.

**Comment by Omicron7** [comment]
👍

**Comment by knutsenm** [comment]
Spot checked in staging; works well. Will deploy tomorrow.

**Pull request merged**
